version: '3'
services:
    honssh:
        build: .
        ports:  # Ineffective, since network_mode is host
            - "22:22"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker:/var/lib/docker
            - /data/honssh/logs:/honssh/logs
        network_mode: "host"

