version: '3'
services:
    honssh:
        build: .
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker:/var/lib/docker
            - /honssh/logs:/honssh/logs
        network_mode: "host"

